version: '3.0'
services:
  cmake:
    image: clo/elmo
    volumes:
      - ../../../:/work
    working_dir: /work/build
    command: cmake /work/src/cpp
          -G Ninja
          -DIGL_INCLUDE_PATH=/libigl/include
          -DEIGEN_INCLUDE_PATH=/eigen

  make:
    image: clo/elmo
    volumes:
      - ../../../:/work
    working_dir: /work/build
    command: ninja
